---
- name: Download Grafana
  get_url:
    url: "{{ grafana_download_url }}"
    dest: /tmp/grafana.tar.gz

- name: Create Grafana installation directory
  file:
    path: "{{ grafana_install_dir }}"
    state: directory
    owner: "{{ file_owner }}"
    group: "{{ file_group }}"
    mode: "{{ file_mode }}"

- name: Extract Grafana
  unarchive:
    src: /tmp/grafana.tar.gz
    dest: "{{ grafana_install_dir }}"
    remote_src: yes

- name: Create Grafana service
  template:
    src: grafana.service.j2
    dest: /etc/systemd/system/{{ grafana_service_name }}.service
  notify:
    - Restart Grafana

- name: Enable and start Grafana service
  systemd:
    name: "{{ grafana_service_name }}"
    enabled: yes
    state: started
    daemon_reload: yes
