---
- name: Create alertmanager user and group
  ansible.builtin.user:
    name: "{{ alertmanager_user }}"
    group: "{{ alertmanager_group }}"
    system: yes
    shell: /usr/sbin/nologin
  when: alertmanager_user != "root"

- name: Set permissions on Alertmanager directory
  file:
    path: "{{ alertmanager_install_dir }}"
    owner: "{{ alertmanager_user }}"
    group: "{{ alertmanager_group }}"
    recurse: yes

- name: Download Alertmanager
  get_url:
    url: "{{ alertmanager_download_url }}"
    dest: "/tmp/alertmanager-{{ alertmanager_version }}.tar.gz"
    mode: '0644'

- name: Create Alertmanager extraction directory
  file:
    path: "{{ alertmanager_install_dir }}"
    state: directory
    mode: '0755'
    owner: "{{ alertmanager_user }}"
    group: "{{ alertmanager_group }}"

- name: Extract Alertmanager
  unarchive:
    src: "/tmp/alertmanager-{{ alertmanager_version }}.tar.gz"
    dest: "{{ alertmanager_install_dir }}"
    remote_src: yes
  args:
    creates: "{{ alertmanager_install_dir }}/alertmanager"

- name: Enable Alertmanager service
  systemd:
    name: alertmanager
    enabled: yes
    state: started

- name: Create Alertmanager configuration file
  template:
    src: "alertmanager.yml.j2"
    dest: "{{ alertmanager_install_dir }}/alertmanager.yml"
    mode: '0644'

- name: Create Alertmanager service file
  copy:
    dest: "{{ alertmanager_service_file }}"
    content: |
      [Unit]
      Description=Alertmanager
      After=network.target

      [Service]
      User={{ alertmanager_user }}
      ExecStart={{ alertmanager_install_dir }}/alertmanager --config.file={{ alertmanager_install_dir }}/alertmanager.yml

      [Install]
      WantedBy=default.target
    mode: '0644'

- name: Enable and start Alertmanager service
  systemd:
    name: alertmanager
    enabled: yes
    state: started
    daemon_reload: true

